name: Kodi Addon-Check2

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  kodi-addon-checker:
    runs-on: ubuntu-latest
    name: Kodi addon checker
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kodi-addon-checker
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Extract repo target
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
