name: Kodi Addon-Check

on:
  pull_request:
    branches-ignore:
      - master

jobs:
  kodi-addon-checker:
    runs-on: ubuntu-latest
    name: Kodi addon checker
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kodi-addon-checker

    - name: Extract repo target
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
